tekton:
  serviceAccountName: tekton-ci

build-image:
  rules:
    - if: vars.CI_COMMIT_BRANCH != 'master'
      when: never
  tekton:
    taskRef: buildah-task
    params:
     - name: IMAGE_URL
       param: BUILDER_IMAGE
       expr: "'quay.io/bigkevmcd/github-tool:' + vars.CI_COMMIT_SHORT_SHA"
