tekton:
  serviceAccountName: tekton-ci

stages:
  - test
  - update-image
  
test-go:
  stage: test
  tekton:
    taskRef: go-test-task

build-image:
  stage: update-image
  rules:
    - if: vars.CI_COMMIT_BRANCH != 'master'
      when: never
  tekton:
    taskRef: buildah
    params:
     - name: IMAGE
       expr: "'quay.io/bigkevmcd/github-tool:master-' + vars.CI_COMMIT_SHORT_SHA"
