# This is just a comment.
image: golang:latest
tekton:
  serviceAccountName: tekton-ci

before_script:
  - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.24.0

stages:
  - test
  - build

format:
  stage: test
  rules:
    - if: vars.CI_COMMIT_BRANCH != 'master'
      when: never
  tekton:
    taskRef: buildah-task
    params:
     - name: IMAGE_URL
       param: BUILDER_IMAGE
       expr: "'quay.io/bigkevmcd/github-tool'"
